db_name = "MEDSTAT.GDB"
username = "sysdba"

host = "192.168.31.161"
port = "3050"
path = "C:\\s"
password = "masterkey"

host_local = "localhost"
port_local = "3050"
path_local = "C:\\s"
password_local = "masterkey"

header_row_height = 180.0
row_height = 100.0

window_height = 0.0
window_width = 0.0
info_timeout = "2.5s"