db_name = "MEDSTAT.GDB"
host = "192.168.0.1"
host_local = "localhost"
info_timeout = "2.5s"
local_mode = false
password = "1"
password_local = "masterkey"
path = "D:\\S\\medstat\\base\\kvartal_2024_1"
path_local = "C:\\Users\\username\\AppData\\Local\\JetBrains\\GoLand2023.3\\tmp\\GoLand"
port = "3050"
port_local = "3050"
username = "sysdba"
window_height = 0.0
window_width = 0.0
update_path = "https://statinfo.com.ua/viewer_updates"