db_name = "MEDSTAT.GDB"
header_row_height = 180.0
host = "192.168.0.1"
password = "1"
path = "D:/s\\medstat\\base\\kvartal_2024_1"
port = "3050"
row_height = 100.0
username = "sysdba"
window_height = 0.0
window_width = 0.0
info_timeout = 2500000000