db_name = "MEDSTAT.GDB"
go_to_update_timeout = "0s"
host = "192.168.0.1"
host_local = "localhost"
info_timeout = "2.5s"
local_mode = true
password = "1"
password_local = "masterkey"
path = "D:\\S\\medstat\\base\\kvartal_2024_1"
path_local = "F:\\projects\\indicator-tables-viewer"
port = "3050"
port_local = "3050"
update_path = "https://statinfo.com.ua/viewer_updates"
username = "sysdba"
window_height = 0.0
window_width = 0.0
